FROM python:3.9

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY streamlit_app.py .

EXPOSE 8501

CMD ["streamlit","run","streamlit_app.py","--server.address","0.0.0.0","--server.port","8501"]